version: "3.9"
   
services:
  db:
    container_name: eris-db
    image: postgres:12.15-bullseye
    ports:
      - "5431:5432"
    restart: always
    volumes:
      - eris_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  web:
    container_name: eris-web
    image: eris-web:1.0
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - /home/jason/github/eris/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  eris_db: