name: black

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.13
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.13
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q -r requirements.txt      
    - uses: psf/black@stable
      with:
        options: "-l 79"